name: pyBEF
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.3.4=py36_0
  - cftime=1.0.3.4
  - fiona=1.8.7
  - gdal=2.4.2
  - geopandas=0.5.1=py_0
  - holoviews=1.12.5=py_0
  - hvplot=0.4.0
  - netcdf4=1.5.1.2
  - numpy=1.17.2
  - panel=0.6.4=py_0
  - proj4=6.1.1
  - requests=2.22.0=py36_1
  - shapely=1.6.4
  - xarray=0.12.3=py_0
