name: pyBEF
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.4.0=py37_0
  - cftime=1.0.3.4
  - fiona=1.8.11
  - gdal=3.0.2
  - geopandas=0.6.1=py_1
  - holoviews=1.12.6=py_0
  - hvplot=0.5.2=py_0
  - numpy=1.17.3
  - panel=0.6.4=py_0
  - requests=2.22.0=py37_1
  - shapely=1.6.4
  - xarray=0.14.0=py_0
